name: deploy project nodejs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: oracle

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy project nodejs
        env:
          PRIVATE: ${{ secrets.PRIVATE }}
          PUBLIC: ${{ vars.PUBLIC }}
        run: |
          echo "Deploying ..."
          echo "PRIVATE: $PRIVATE"
          echo "PUBLIC: $PUBLIC"
          echo "All Done !!!"

      - name: Update .env with GitHub environment variable
        run: |
          cat .env
          echo "PRIVATE=$PRIVATE" >> .env
          echo "PUBLIC=$PUBLIC" >> .env
