name: deploy project nodejs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy project nodejs
        # env:
        #   SERVERID: ${{ vars.SERVERID }}
        #   PASS: ${{vars.PASS}}
        #   GIT_PASS: ${{vars.GIT_PASS}}
        run: |
          # sudo apt-get install -y openssh-client
          # sudo apt-get install sshpass
          echo "Deploying ..."
          # sshpass -p $PASS ssh -o StrictHostKeyChecking=no root@$SERVERID "cd ./saas-backend/ && rm pnpm-lock.yaml && git pull && ./build.sh"
          echo "All Done !!!"
